language: generic
services:
  - docker

before_install:
  - docker build -t lemillion/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run --rm -e CI=true lemillion/react-test npm test

after_success:
  - docker build -t lemillion/fibonacci-client ./client
  - docker build -t lemillion/fibonacci-nginx ./nginx
  - docker build -t lemillion/fibonacci-server ./server
  - docker build -t lemillion/fibonacci-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lemillion/fibonacci-client
  - docker push lemillion/fibonacci-nginx
  - docker push lemillion/fibonacci-server
  - docker push lemillion/fibonacci-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: docker-fibonacci
  env: DockerFibonacci-env
  bucket_name: elasticbeanstalk-us-west-1-657468154737
  bucket_path: docker-fibonacci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
